### PR TITLE
Fix GHC-8.10.4 build

### PR DESCRIPTION
**Pull request by TristanCacqueray**
This change enables building the graphics example with ghc-8.10.4
and cabal-install-3.4.0.0 with: `cabal build -O2 graphics-examples`

### CODE REVIEW

**Comment by conal** [comment]
Thanks very much for this contribution.

Is it somehow more relevant to graphics examples than the others?

What motivated you to add an argument to `satisy` and `satisfy'`?

**Comment by TristanCacqueray** [comment]
I meant that I haven't tested the other examples, I just went through the compilation errors until the graphics demo produced the `out/shaders/annulus2.html` file.

I can't tell why, but adding an argument to `satisfy` fixed that error:
```
src/ConCat/Satisfy.hs:17:11: error:
    • Cannot instantiate unification variable ‘a1’
      with a type involving polytypes: (c => z) -> z
        GHC doesn't yet support impredicative polymorphism
    • In the expression:
        error "satisfy: Use -fplugin=ConCat.Satisfy.Plugin"
      In an equation for ‘satisfy’:
          satisfy = error "satisfy: Use -fplugin=ConCat.Satisfy.Plugin"
    • Relevant bindings include
        satisfy :: (c => z) -> z (bound at src/ConCat/Satisfy.hs:17:1)
   |
17 | satisfy = error "satisfy: Use -fplugin=ConCat.Satisfy.Plugin"
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by conal** [comment]
Wow. All of the graphics examples work again. Thanks!!

**Comment by TristanCacqueray** [comment]
You are welcome, thank you for publishing this project!

**Pull request merged**
