### PR TITLE
Refactor rebox rules to avoid looping in newer GHCs

### PR DESCRIPTION
**Pull request by osa1**
Current reboxing rules cause newer GHCs (8.2, 8.4, HEAD) to loop. Here's
an example trace of GHC's simplifier that demonstrates the loop:

Original expression:

    1.0## /## 2.0##

(1) (/##) rule applies + follow-up simplifications:

    (\u# v# -> unboxD (GHC.Float.divideDouble (boxD u#) (boxD v#)))
        1.0## 2.0##

(2) Inline unboxD

    (\u# v# -> (\(D# d#) -> d#) (GHC.Float.divideDouble (boxD u#) (boxD v#)))
        1.0## 2.0##

(3) Inline divideDouble

    (\u# v# -> (\(D# d#) -> d#) ((\(D# x) (D# y) -> D# (x /## y)) (boxD u#) (boxD v#)))
        1.0## 2.0##

Now we again have a (/##) so our rule applies again, leading to a loop. At this
point GHC inlines boxD

(4) Inline boxD (x2)

    (\u# v# -> (\(D# d#) -> d#) ((\(D# x) (D# y) -> D# (x /## y)) (D# u#) (D# v#)))
        1.0## 2.0##

... and applies our rule again.

GHC 8.0 doesn't do any simplifications during step (1), so after (/##)
rule we get

    (\u# v# -> unboxD (GHC.Real./ @ Double $fFractionalDouble (boxD u#) (boxD v#)))
      1.0## 2.0##

Now our `CatifyC` rule applies, eliminating `GHC.Real./` and avoiding
the loop.

It turns out a similar case happened with GHC 8.0 too, as this comment
in Rebox.hs indicates:

    -- Generating truncateC instead of truncate to avoid an infinite rewrite loop
    -- between these rules and GHC's "truncate/Double->Int" and
    -- "truncate/Float->Int" rule. Maybe change all of the generated functions to be
    -- the categorical versions to more robustly avoid such loops. This change would
    -- make rewriting a little more efficient as well, since operations like
    -- truncate would get rewritten to their counterparts like truncateC anyway.

This is exactly what this patch does to rest of the operators.

(also fixes a few small bugs in rules where `ge` was mapped to `>`
rather than `>=` etc.)

### CODE REVIEW

**Comment by conal** [comment]
Thanks very much for tracking this one down!

**Comment by isovector** [comment]
Heads up: I think either this or 4afd8885fe8db9aeb20d5c7174ae98a9b8f203b9 might have caused a regression in GHC 8.0.2. I'm seeing some egregious compile times since merging to HEAD, my module which used to take 10 minutes has now been going for 1h+ and shows no signs of stopping.

**Comment by osa1** [comment]
Interesting. It'd be helpful if you could share a reproducer. Usually unless you have `-fsimpl-tick-factor=0` you get a "ticks exhausted" panic when rules get into a loop, so maybe this is something else (maybe an exponential behavior in the simplifier? Something like https://github.com/ghc/ghc/commit/9b58c6360b9c2dc5b15c17ba83f5dc729efb84dc).

**Comment by isovector** [comment]
I think you might be right; sorry for the false alarm. I'm getting ridiculous compile times now even when I revert this change :/ Something spooky is going on.

**Comment by conal** [comment]
@isovector I've not yet noticed a compilation slow-down. Can you point to some long-compiling examples so I can try also?

**Pull request merged**
