### PR TITLE
Re-introduce `Strong`.

### PR DESCRIPTION
**Pull request by sellout**
In our fork of the plugin we take advantage of this to convert functors
and applicatives. The slightly different requirements (e.g., in
**Hask**, all functors are Strong, but not necessarily Pointed) made me
avoid the Translators approach.

### CODE REVIEW

**Comment by sellout** [comment]
Wondering if this could be merged, or if there are any issues with it. (E.g., why was `Strong` commented out in the first place?)

**Comment by conal** [comment]
Thanks for the reminder! I've forgotten why I commented out `Strong`.

@mikesperber Would you mind giving this PR a go with your uses of concat? I'd like to merge but not break what you're up to.

**Comment by mikesperber** [comment]
> @mikesperber Would you mind giving this PR a go with your uses of concat? I'd like to merge but not break what you're up to.

Go! (I don't see any interaction with what we do.)

**Comment by conal** [comment]
Thanks for the assessment, Mike.

Merged.

**Pull request merged**
